// For description of these values see http://adblockplus.org/en/preferences

pref("extensions.adblocklite.currentVersion", "0.0");
pref("extensions.adblocklite.enabled", true);
pref("extensions.adblocklite.frameobjects", true);
pref("extensions.adblocklite.fastcollapse", false);
pref("extensions.adblocklite.showintoolbar", true);
pref("extensions.adblocklite.showinstatusbar", false);
pref("extensions.adblocklite.detachsidebar", false);
pref("extensions.adblocklite.synchronizationinterval", 24);
pref("extensions.adblocklite.defaulttoolbaraction", 0);
pref("extensions.adblocklite.defaultstatusbaraction", 0);
pref("extensions.adblocklite.sidebar_key", "Accel Shift V");
pref("extensions.adblocklite.sendReport_key", "");
pref("extensions.adblocklite.settings_key", "Accel Shift E, Accel Shift F, Accel Shift O");
pref("extensions.adblocklite.enable_key", "");
pref("extensions.adblocklite.flash_scrolltoitem", true);
pref("extensions.adblocklite.previewimages", true);
pref("extensions.adblocklite.data_directory", "adblocklite");
pref("extensions.adblocklite.patternsbackups", 5);
pref("extensions.adblocklite.patternsbackupinterval", 24);
pref("extensions.adblocklite.whitelistschemes", "about chrome file irc moz-safe-about news resource snews x-jsd addbook cid imap mailbox nntp pop data javascript moz-icon");
pref("extensions.adblocklite.hideimagemanager", true);
pref("extensions.adblocklite.subscriptions_listurl", "https://adblockplus.org/subscriptions.xml");
pref("extensions.adblocklite.subscriptions_fallbackurl", "https://adblockplus.org/getSubscription?version=%VERSION%&url=%SUBSCRIPTION%&downloadURL=%URL%&error=%ERROR%&channelStatus=%CHANNELSTATUS%&responseStatus=%RESPONSESTATUS%");
pref("extensions.adblocklite.subscriptions_fallbackerrors", 5);
pref("extensions.adblocklite.documentation_link", "https://adblockplus.org/redirect?link=%LINK%&lang=%LANG%");
pref("extensions.adblocklite.savestats", true);
pref("extensions.adblocklite.composer_default", 2);
pref("extensions.adblocklite.clearStatsOnHistoryPurge", true);
pref("extensions.adblocklite.report_submiturl", "https://reports.adblockplus.org/submitReport?version=1&guid=%GUID%&lang=%LANG%");
pref("extensions.adblocklite.recentReports", "[]");
pref("services.sync.engine.adblockplus", false);
