regedit /s Y:\sources\reg\sys.reg
regedit /s Y:\sources\reg\soft.reg
sc delete wmiApSrv
sc delete WbioSrvc
sc delete vss
sc delete swprv
sc delete trustedinstaller
sc delete msiscsi
sc delete bdesvc
sc delete appinfo
sc delete CryptSvc
sc delete wbengine
sc delete mpsSvc
sc delete AudioEndpointBuilder
sc delete audiosrv
sc delete defragsvc
sc delete bdesvc
sc delete pdagent
sc delete pdengine
sc delete imdsksvc
exit