rmdir /s /q "X:\Windows\Security\"
rmdir /s /q "X:\Windows\ServiceProfiles\"
del /f /a:h "X:\$WIMDESC"
rmdir /s /q "X:\Windows\system32\Logfiles\"
rmdir /s /q "X:\Windows\system32\Microsoft\"
imdisk -a -s 20%% -m B: -p "/fs:fat32 /q /y"
mkdir "b:\temp"
regsvr32 /i /s Query.dll
regsvr32 /i /s "%SystemRoot%\System32\netshell.dll"
regsvr32 /i /s "%SystemRoot%\System32\networkexplorer.dll"
regsvr32 /i /s "%systemdrive%\Program Files\HashTab\HashTab32.dll"
regsvr32 /i /s "%systemdrive%\Program Files\ExtremeCopy\XCShellExt.dll"
regsvr32 /i /s ieproxy.dll
regsvr32 /i /s "%systemdrive%\Program Files\XNView\XnViewShellExt.dll"
if not EXIST "B:\Programs\" mkdir "B:\Programs\"
if EXIST "b:\temp" regedit /s "%systemroot%\system32\temp.reg" 
