pref("extensions.tacache.cache", "[]");
pref("extensions.tacache.interval", 5);
pref("extensions.tacache.saveInterval", 60);
pref("extensions.tacache.clearCache", 1);
pref("extensions.tacache.restartClearInMin", 5);
pref("extensions.tacache.clearTimeSpan", 1);
pref("extensions.tacache.clearWithSanitize", true);
pref("extensions.tacache.maxTextSaved", 20);
pref("extensions.tacache.statusButton", true);
pref("extensions.tacache.whitelist", "docs.google.com spreadsheets.google.com");
